In [3]:
import pandas as pd
import matplotlib.pyplot as plt

In [3]:
data = pd.read_csv('sample_size_ssims_200.csv')

In [4]:
path2 = '/home/miguel/GI/1 - Segmentation/UNet-and-Synthesis-Results/unet_performance_statistics/model-none-synthetic-real-ratio-0-roberta-6-18/fold_3/validation_per_subj_statistics.csv'

In [5]:
subj_data = pd.read_csv(path2)

In [8]:
subj_data = subj_data[subj_data['epoch'] == 99]

In [14]:
print('Mean Dice Coefficient:', subj_data['dice_coefficient'].mean())
print('Percent Dice > 0.8:', (subj_data['dice_coefficient'] > 0.8).mean())

Mean Dice Coefficient: 0.8750848972490526
Percent Dice > 0.8: 0.8518518518518519

In [ ]:
subj_data['dice_coefficient']

                        case_day  dice_coefficient  epoch
7128   FD-027-slice-02-image.png      1.000000e+00     99
7129   FD-027-slice-07-image.png      1.271028e-01     99
7130   FD-027-slice-10-image.png      9.093787e-01     99
7131   FD-027-slice-15-image.png      7.465096e-01     99
7132   FD-027-slice-17-image.png      8.528723e-01     99
...                          ...               ...    ...
31315  FD-032-slice-49-image.png      8.760766e-01     99
31316  FD-032-slice-54-image.png      7.801858e-01     99
31317  FD-032-slice-58-image.png      7.235890e-10     99
31318  FD-032-slice-67-image.png      1.000000e+00     99
31319  FD-032-slice-69-image.png      1.000000e+00     99

[216 rows x 3 columns]

In [1]:
import os

In [4]:
folders = os.listdir('/home/miguel/GI/1.5 - Synthetic Data Generation/Singan-Seg/TrainedModels')

In [8]:
len([folder for folder in folders if 'FD' in folder])

106

In [12]:
import os
import pandas as pd

In [13]:
folder_path = '/home/miguel/GI/1 - Segmentation/UNet-and-Synthesis-Results/unet_performance_statistics/model-none-synthetic-real-ratio-0-roberta-6-18'

In [15]:
data

      FD-029-slice-01-image.png  1.525878902397526e-11   0
0     FD-029-slice-02-image.png           1.526881e-11   0
1     FD-029-slice-03-image.png           1.526648e-11   0
2     FD-029-slice-04-image.png           1.526951e-11   0
3     FD-029-slice-05-image.png           1.527394e-11   0
4     FD-029-slice-06-image.png           1.529730e-11   0
...                         ...                    ...  ..
7410  FD-029-slice-68-image.png           1.000000e+00  99
7411  FD-029-slice-69-image.png           1.000000e+00  99
7412  FD-029-slice-70-image.png           1.000000e+00  99
7413  FD-029-slice-71-image.png           1.000000e+00  99
7414  FD-029-slice-72-image.png           1.000000e+00  99

[7415 rows x 3 columns]

In [43]:
for folder in os.listdir(folder_path):
    if 'FD' in folder:
        print(folder)
        path = os.path.join(folder_path, folder, 'cv_validation_per_subj_statistics.csv')
        if os.path.exists(path):
            data = pd.read_csv(path, header=None)
            data.columns = ["filename", 'dice_coefficient', 'epoch']
            data = data[(data['epoch'] == 99)]
            print('Mean Dice Coefficient:', data['dice_coefficient'].mean())
            print('Percent Dice > 0.8:', (data['dice_coefficient'] > 0.8).mean())
        else:
            print(f"File {path} does not exist.")
        print()

fold_FD-032
Mean Dice Coefficient: 0.5708373450437696
Percent Dice > 0.8: 0.4166666666666667

fold_FD-029
Mean Dice Coefficient: 0.7555634129043582
Percent Dice > 0.8: 0.5

fold_FD-027
Mean Dice Coefficient: 0.7420752136051032
Percent Dice > 0.8: 0.5694444444444444

fold_FD-031
Mean Dice Coefficient: 0.852955262354103
Percent Dice > 0.8: 0.75

fold_FD-030
Mean Dice Coefficient: 0.8089245743241124
Percent Dice > 0.8: 0.7361111111111112

In [27]:
data = pd.read_csv(path, header=None)

In [38]:
data[data['epoch'] == '99']

                       filename dice_coefficient epoch
7446  FD-032-slice-01-image.png              1.0    99
7447  FD-032-slice-02-image.png              1.0    99
7448  FD-032-slice-03-image.png              1.0    99
7449  FD-032-slice-04-image.png              1.0    99
7450  FD-032-slice-05-image.png              1.0    99
...                         ...              ...   ...
7513  FD-032-slice-68-image.png              1.0    99
7514  FD-032-slice-69-image.png              1.0    99
7515  FD-032-slice-70-image.png              1.0    99
7516  FD-032-slice-71-image.png              1.0    99
7517  FD-032-slice-72-image.png              1.0    99

[72 rows x 3 columns]

In [37]:
data['epoch'].values[-1]

'99'