In [13]:
import os
import numpy as np
import pandas as pd

In [6]:
TRAINED_MODELS_PATH = '/home/miguel/GI/1.5 - Synthetic Data Generation/Singan-Seg/TrainedModels'
RANDOM_SAMPLES_PY = '/home/miguel/GI/1.5 - Synthetic Data Generation/Singan-Seg/random_samples.py'
FULL_DATASET_FOLDER_PATH = '/home/miguel/GI/0 - Data Exploration & Analysis/GI-Roberta/gi-roberta-dataset/full_dataset_rgba'
OUTPUT_FOLDER_PATH = 'Output_benchmark'
RANDOM_SAMPLES = '/home/miguel/GI/1.5 - Synthetic Data Generation/Singan-Seg/Output_benchmark/RandomSamples'

In [16]:
trained_models = [f for f in os.listdir(TRAINED_MODELS_PATH) if os.path.isdir(os.path.join(TRAINED_MODELS_PATH, f)) and 'FD' in f]

In [17]:
model_names = np.unique([f.split('-slice')[0] for f in trained_models])

In [19]:
trained_models_and_model_names = pd.DataFrame({
    'model_name': [f.split('-slice')[0] for f in trained_models],
    'trained_model': trained_models
})

In [20]:
trained_models_and_model_names

    model_name          trained_model
0       FD-030  FD-030-slice-18-image
1       FD-029  FD-029-slice-24-image
2       FD-032  FD-032-slice-38-image
3       FD-029  FD-029-slice-04-image
4       FD-030  FD-030-slice-27-image
..         ...                    ...
109     FD-027  FD-027-slice-66-image
110     FD-032  FD-032-slice-33-image
111     FD-027  FD-027-slice-54-image
112     FD-032  FD-032-slice-39-image
113     FD-030  FD-030-slice-37-image

[114 rows x 2 columns]

In [34]:
singan_ssim_results = pd.read_csv('/home/miguel/GI/1.5 - Synthetic Data Generation/Singan-Seg/singan_ssim_results.csv')

In [35]:
singan_ssim_results['model_name'] = [f.split('-slice')[0] for f in singan_ssim_results['image_name']]

In [36]:
singan_ssim_results = singan_ssim_results[singan_ssim_results['num_samples_gt_0_5'] > 3]

In [38]:
singan_ssim_results['model_name'].value_counts()

model_name
FD-030    16
FD-031    14
FD-029    11
FD-032     7
FD-027     5
Name: count, dtype: int64

In [40]:
for model_name in model_names:
    trained_models_and_model_names_df = trained_models_and_model_names[trained_models_and_model_names['model_name'] == model_name]
    synthesis_models = trained_models_and_model_names_df['trained_model'].unique()

In [41]:
synthesis_models

array(['FD-032-slice-38-image', 'FD-032-slice-50-image',
       'FD-032-slice-55-image', 'FD-032-slice-20-image',
       'FD-032-slice-27-image', 'FD-032-slice-28-image',
       'FD-032-slice-29-image', 'FD-032-slice-58-image',
       'FD-032-slice-72-image', 'FD-032-slice-21-image',
       'FD-032-slice-11-image', 'FD-032-slice-04-image',
       'FD-032-slice-37-image', 'FD-032-slice-32-image',
       'FD-032-slice-34-image', 'FD-032-slice-06-image',
       'FD-032-slice-33-image', 'FD-032-slice-39-image'], dtype=object)

In [22]:
trained_models_and_model_names_df

    model_name          trained_model
2       FD-032  FD-032-slice-38-image
9       FD-032  FD-032-slice-50-image
20      FD-032  FD-032-slice-55-image
23      FD-032  FD-032-slice-20-image
26      FD-032  FD-032-slice-27-image
35      FD-032  FD-032-slice-28-image
43      FD-032  FD-032-slice-29-image
45      FD-032  FD-032-slice-58-image
48      FD-032  FD-032-slice-72-image
60      FD-032  FD-032-slice-21-image
63      FD-032  FD-032-slice-11-image
64      FD-032  FD-032-slice-04-image
81      FD-032  FD-032-slice-37-image
83      FD-032  FD-032-slice-32-image
84      FD-032  FD-032-slice-34-image
101     FD-032  FD-032-slice-06-image
110     FD-032  FD-032-slice-33-image
112     FD-032  FD-032-slice-39-image

In [46]:
images

['FD-032-slice-04-image.png',
 'FD-027-slice-71-image.png',
 'FD-027-slice-24-image.png',
 'FD-027-slice-47-image.png',
 'FD-031-slice-16-image.png',
 'FD-031-slice-27-image.png',
 'FD-027-slice-20-image.png',
 'FD-027-slice-13-image.png',
 'FD-031-slice-07-image.png',
 'FD-027-slice-26-image.png',
 'FD-027-slice-40-image.png',
 'FD-032-slice-11-image.png',
 'FD-027-slice-55-image.png',
 'FD-027-slice-14-image.png',
 'FD-027-slice-49-image.png',
 'FD-030-slice-25-image.png',
 'FD-030-slice-37-image.png',
 'FD-031-slice-65-image.png',
 'FD-032-slice-72-image.png',
 'FD-027-slice-29-image.png',
 'FD-029-slice-18-image.png',
 'FD-029-slice-07-image.png',
 'FD-029-slice-72-image.png',
 'FD-032-slice-50-image.png',
 'FD-030-slice-39-image.png',
 'FD-031-slice-53-image.png',
 'FD-029-slice-61-image.png',
 'FD-032-slice-39-image.png',
 'FD-029-slice-31-image.png',
 'FD-030-slice-18-image.png',
 'FD-027-slice-66-image.png',
 'FD-031-slice-21-image.png',
 'FD-031-slice-72-image.png',
 'FD-032-slice-33-image.png',
 'FD-030-slice-05-image.png',
 'FD-029-slice-43-image.png',
 'FD-032-slice-28-image.png',
 'FD-031-slice-50-image.png',
 'FD-030-slice-20-image.png',
 'FD-030-slice-63-image.png',
 'FD-030-slice-32-image.png',
 'FD-030-slice-42-image.png',
 'FD-030-slice-35-image.png',
 'FD-031-slice-31-image.png',
 'FD-030-slice-15-image.png',
 'FD-032-slice-55-image.png',
 'FD-027-slice-27-image.png',
 'FD-031-slice-63-image.png',
 'FD-029-slice-24-image.png',
 'FD-030-slice-72-image.png',
 'FD-031-slice-69-image.png',
 'FD-029-slice-60-image.png',
 'FD-027-slice-07-image.png',
 'FD-030-slice-70-image.png',
 'FD-031-slice-10-image.png',
 'FD-029-slice-62-image.png',
 'FD-030-slice-09-image.png',
 'FD-030-slice-61-image.png',
 'FD-032-slice-27-image.png',
 'FD-030-slice-45-image.png',
 'FD-029-slice-69-image.png',
 'FD-030-slice-56-image.png',
 'FD-031-slice-44-image.png',
 'FD-027-slice-50-image.png',
 'FD-031-slice-01-image.png',
 'FD-027-slice-21-image.png',
 'FD-030-slice-03-image.png',
 'FD-027-slice-69-image.png',
 'FD-027-slice-41-image.png',
 'FD-029-slice-05-image.png',
 'FD-027-slice-25-image.png',
 'FD-030-slice-69-image.png',
 'FD-027-slice-63-image.png',
 'FD-029-slice-67-image.png',
 'FD-029-slice-40-image.png',
 'FD-032-slice-32-image.png',
 'FD-029-slice-42-image.png',
 'FD-030-slice-40-image.png',
 'FD-030-slice-67-image.png',
 'FD-032-slice-21-image.png',
 'FD-032-slice-37-image.png',
 'FD-032-slice-38-image.png',
 'FD-031-slice-61-image.png',
 'FD-030-slice-27-image.png',
 'FD-032-slice-06-image.png',
 'FD-031-slice-67-image.png',
 'FD-029-slice-32-image.png',
 'FD-027-slice-02-image.png',
 'FD-029-slice-04-image.png',
 'FD-027-slice-36-image.png',
 'FD-032-slice-34-image.png',
 'FD-029-slice-12-image.png',
 'FD-029-slice-59-image.png',
 'FD-030-slice-12-image.png',
 'FD-032-slice-58-image.png',
 'FD-031-slice-68-image.png',
 'FD-031-slice-15-image.png',
 'FD-027-slice-19-image.png',
 'FD-031-slice-35-image.png',
 'FD-030-slice-64-image.png',
 'FD-029-slice-33-image.png',
 'FD-027-slice-54-image.png',
 'FD-032-slice-29-image.png',
 'FD-027-slice-52-image.png',
 'FD-031-slice-34-image.png',
 'FD-031-slice-66-image.png',
 'FD-031-slice-20-image.png',
 'FD-027-slice-56-image.png',
 'FD-032-slice-20-image.png',
 'FD-027-slice-17-image.png',
 'FD-027-slice-43-image.png',
 'FD-029-slice-29-image.png',
 'FD-030-slice-62-image.png',
 'FD-030-slice-22-image.png',
 'FD-031-slice-45-image.png',
 'FD-031-slice-11-image.png',
 'FD-031-slice-28-image.png',
 'FD-029-slice-57-image.png',
 'FD-032-slice-53-image.png',
 'FD-029-slice-50-image.png',
 'FD-030-slice-44-image.png',
 'FD-032-slice-45-image.png',
 'FD-031-slice-29-image.png',
 'FD-029-slice-46-image.png',
 'FD-032-slice-43-image.png',
 'FD-029-slice-03-image.png',
 'FD-027-slice-72-image.png',
 'FD-027-slice-30-image.png',
 'FD-031-slice-52-image.png',
 'FD-027-slice-37-image.png',
 'FD-032-slice-54-image.png',
 'FD-031-slice-37-image.png',
 'FD-032-slice-14-image.png',
 'FD-032-slice-25-image.png',
 'FD-029-slice-06-image.png',
 'FD-029-slice-13-image.png',
 'FD-027-slice-10-image.png',
 'FD-029-slice-54-image.png',
 'FD-031-slice-41-image.png',
 'FD-032-slice-35-image.png',
 'FD-027-slice-28-image.png',
 'FD-029-slice-37-image.png',
 'FD-032-slice-24-image.png',
 'FD-032-slice-23-image.png',
 'FD-027-slice-18-image.png',
 'FD-027-slice-59-image.png',
 'FD-027-slice-08-image.png',
 'FD-027-slice-16-image.png',
 'FD-027-slice-51-image.png',
 'FD-032-slice-42-image.png',
 'FD-029-slice-08-image.png',
 'FD-030-slice-43-image.png',
 'FD-031-slice-25-image.png',
 'FD-029-slice-26-image.png',
 'FD-032-slice-05-image.png',
 'FD-031-slice-47-image.png',
 'FD-032-slice-31-image.png',
 'FD-027-slice-60-image.png',
 'FD-030-slice-54-image.png',
 'FD-027-slice-46-image.png',
 'FD-032-slice-46-image.png',
 'FD-030-slice-19-image.png',
 'FD-027-slice-15-image.png',
 'FD-031-slice-58-image.png',
 'FD-027-slice-12-image.png',
 'FD-029-slice-49-image.png',
 'FD-031-slice-02-image.png',
 'FD-032-slice-01-image.png',
 'FD-032-slice-08-image.png',
 'FD-027-slice-44-image.png',
 'FD-027-slice-23-image.png',
 'FD-029-slice-02-image.png',
 'FD-032-slice-52-image.png',
 'FD-029-slice-63-image.png',
 'FD-031-slice-09-image.png',
 'FD-030-slice-07-image.png',
 'FD-032-slice-66-image.png',
 'FD-029-slice-30-image.png',
 'FD-027-slice-39-image.png',
 'FD-032-slice-62-image.png',
 'FD-030-slice-21-image.png',
 'FD-030-slice-52-image.png',
 'FD-030-slice-17-image.png',
 'FD-032-slice-49-image.png',
 'FD-030-slice-31-image.png',
 'FD-032-slice-03-image.png',
 'FD-032-slice-63-image.png',
 'FD-030-slice-48-image.png',
 'FD-030-slice-47-image.png',
 'FD-032-slice-41-image.png',
 'FD-032-slice-26-image.png',
 'FD-031-slice-60-image.png',
 'FD-031-slice-30-image.png',
 'FD-029-slice-52-image.png',
 'FD-029-slice-35-image.png',
 'FD-032-slice-36-image.png',
 'FD-031-slice-08-image.png',
 'FD-029-slice-19-image.png',
 'FD-029-slice-71-image.png',
 'FD-030-slice-49-image.png',
 'FD-029-slice-28-image.png',
 'FD-032-slice-56-image.png',
 'FD-029-slice-14-image.png',
 'FD-030-slice-28-image.png',
 'FD-032-slice-19-image.png',
 'FD-031-slice-24-image.png',
 'FD-031-slice-56-image.png',
 'FD-031-slice-55-image.png',
 'FD-031-slice-46-image.png',
 'FD-032-slice-30-image.png',
 'FD-032-slice-67-image.png',
 'FD-030-slice-08-image.png',
 'FD-029-slice-17-image.png',
 'FD-027-slice-38-image.png',
 'FD-031-slice-48-image.png',
 'FD-030-slice-23-image.png',
 'FD-027-slice-34-image.png',
 'FD-027-slice-48-image.png',
 'FD-032-slice-61-image.png',
 'FD-031-slice-13-image.png',
 'FD-027-slice-11-image.png',
 'FD-029-slice-65-image.png',
 'FD-032-slice-17-image.png',
 'FD-027-slice-31-image.png',
 'FD-032-slice-13-image.png',
 'FD-027-slice-68-image.png',
 'FD-030-slice-11-image.png',
 'FD-032-slice-12-image.png',
 'FD-029-slice-16-image.png',
 'FD-027-slice-67-image.png',
 'FD-027-slice-62-image.png',
 'FD-032-slice-44-image.png',
 'FD-029-slice-51-image.png',
 'FD-031-slice-18-image.png',
 'FD-029-slice-38-image.png',
 'FD-032-slice-18-image.png',
 'FD-029-slice-11-image.png',
 'FD-027-slice-03-image.png',
 'FD-029-slice-44-image.png',
 'FD-032-slice-47-image.png',
 'FD-032-slice-02-image.png',
 'FD-030-slice-71-image.png',
 'FD-029-slice-41-image.png',
 'FD-031-slice-62-image.png',
 'FD-031-slice-23-image.png',
 'FD-030-slice-57-image.png',
 'FD-030-slice-04-image.png',
 'FD-029-slice-39-image.png',
 'FD-027-slice-35-image.png',
 'FD-031-slice-51-image.png',
 'FD-031-slice-43-image.png',
 'FD-029-slice-55-image.png',
 'FD-032-slice-22-image.png',
 'FD-030-slice-59-image.png',
 'FD-030-slice-29-image.png',
 'FD-030-slice-46-image.png',
 'FD-029-slice-27-image.png',
 'FD-032-slice-10-image.png',
 'FD-031-slice-40-image.png',
 'FD-031-slice-38-image.png',
 'FD-031-slice-54-image.png',
 'FD-029-slice-20-image.png',
 'FD-031-slice-14-image.png',
 'FD-031-slice-71-image.png',
 'FD-031-slice-64-image.png',
 'FD-029-slice-34-image.png',
 'FD-032-slice-09-image.png',
 'FD-027-slice-53-image.png',
 'FD-027-slice-22-image.png',
 'FD-029-slice-23-image.png',
 'FD-029-slice-64-image.png',
 'FD-030-slice-13-image.png',
 'FD-032-slice-69-image.png',
 'FD-030-slice-53-image.png',
 'FD-030-slice-68-image.png',
 'FD-030-slice-66-image.png',
 'FD-027-slice-33-image.png',
 'FD-032-slice-40-image.png',
 'FD-027-slice-06-image.png',
 'FD-030-slice-51-image.png',
 'FD-029-slice-53-image.png',
 'FD-031-slice-59-image.png',
 'FD-027-slice-65-image.png',
 'FD-031-slice-05-image.png',
 'FD-032-slice-68-image.png',
 'FD-029-slice-66-image.png',
 'FD-031-slice-70-image.png',
 'FD-031-slice-22-image.png',
 'FD-029-slice-48-image.png',
 'FD-030-slice-60-image.png',
 'FD-030-slice-01-image.png',
 'FD-030-slice-26-image.png',
 'FD-029-slice-09-image.png',
 'FD-027-slice-09-image.png',
 'FD-032-slice-07-image.png',
 'FD-029-slice-70-image.png',
 'FD-029-slice-21-image.png',
 'FD-027-slice-45-image.png',
 'FD-027-slice-32-image.png',
 'FD-027-slice-04-image.png',
 'FD-032-slice-70-image.png',
 'FD-032-slice-65-image.png',
 'FD-030-slice-34-image.png',
 'FD-031-slice-03-image.png',
 'FD-031-slice-17-image.png',
 'FD-031-slice-04-image.png',
 'FD-027-slice-01-image.png',
 'FD-030-slice-41-image.png',
 'FD-031-slice-49-image.png',
 'FD-031-slice-06-image.png',
 'FD-030-slice-33-image.png',
 'FD-027-slice-57-image.png',
 'FD-029-slice-68-image.png',
 'FD-030-slice-65-image.png',
 'FD-031-slice-39-image.png',
 'FD-029-slice-01-image.png',
 'FD-030-slice-10-image.png',
 'FD-029-slice-15-image.png',
 'FD-029-slice-47-image.png',
 'FD-030-slice-50-image.png',
 'FD-030-slice-30-image.png',
 'FD-029-slice-10-image.png',
 'FD-031-slice-12-image.png',
 'FD-031-slice-57-image.png',
 'FD-029-slice-22-image.png',
 'FD-027-slice-05-image.png',
 'FD-032-slice-59-image.png',
 'FD-029-slice-45-image.png',
 'FD-030-slice-55-image.png',
 'FD-032-slice-71-image.png',
 'FD-027-slice-58-image.png',
 'FD-031-slice-36-image.png',
 'FD-030-slice-06-image.png',
 'FD-032-slice-15-image.png',
 'FD-030-slice-02-image.png',
 'FD-031-slice-32-image.png',
 'FD-032-slice-60-image.png',
 'FD-030-slice-36-image.png',
 'FD-031-slice-19-image.png',
 'FD-030-slice-16-image.png',
 'FD-027-slice-61-image.png',
 'FD-027-slice-42-image.png',
 'FD-032-slice-64-image.png',
 'FD-032-slice-48-image.png',
 'FD-027-slice-64-image.png',
 'FD-029-slice-56-image.png',
 'FD-031-slice-42-image.png',
 'FD-032-slice-51-image.png',
 'FD-030-slice-38-image.png',
 'FD-027-slice-70-image.png',
 'FD-029-slice-25-image.png',
 'FD-030-slice-58-image.png',
 'FD-031-slice-33-image.png',
 'FD-029-slice-36-image.png',
 'FD-031-slice-26-image.png',
 'FD-030-slice-14-image.png',
 'FD-029-slice-58-image.png',
 'FD-030-slice-24-image.png',
 'FD-032-slice-16-image.png',
 'FD-032-slice-57-image.png']

In [44]:
images = os.listdir(FULL_DATASET_FOLDER_PATH)

In [48]:
image_datas = pd.DataFrame({
    'file_name': images,
    'model_name': [f.split('-slice')[0] for f in images]
})

In [49]:
image_datas

                     file_name model_name
0    FD-032-slice-04-image.png     FD-032
1    FD-027-slice-71-image.png     FD-027
2    FD-027-slice-24-image.png     FD-027
3    FD-027-slice-47-image.png     FD-027
4    FD-031-slice-16-image.png     FD-031
..                         ...        ...
355  FD-030-slice-14-image.png     FD-030
356  FD-029-slice-58-image.png     FD-029
357  FD-030-slice-24-image.png     FD-030
358  FD-032-slice-16-image.png     FD-032
359  FD-032-slice-57-image.png     FD-032

[360 rows x 2 columns]

In [50]:
trained_models_and_model_names_df

    model_name          trained_model
2       FD-032  FD-032-slice-38-image
9       FD-032  FD-032-slice-50-image
20      FD-032  FD-032-slice-55-image
23      FD-032  FD-032-slice-20-image
26      FD-032  FD-032-slice-27-image
35      FD-032  FD-032-slice-28-image
43      FD-032  FD-032-slice-29-image
45      FD-032  FD-032-slice-58-image
48      FD-032  FD-032-slice-72-image
60      FD-032  FD-032-slice-21-image
63      FD-032  FD-032-slice-11-image
64      FD-032  FD-032-slice-04-image
81      FD-032  FD-032-slice-37-image
83      FD-032  FD-032-slice-32-image
84      FD-032  FD-032-slice-34-image
101     FD-032  FD-032-slice-06-image
110     FD-032  FD-032-slice-33-image
112     FD-032  FD-032-slice-39-image

In [51]:
image_path = '/home/miguel/GI/1 - Segmentation/UNet-and-Synthesis-Results/unet_singan_augmented_datasets/augmented_dataset_expansion_factor_0.5/FD-027/FD-027-slice-16-image.png'